CREATE DATABASE pokemon;

USE pokemon;

CREATE TABLE name_type (
                           id INT PRIMARY KEY AUTO_INCREMENT,
                           name VARCHAR(25) NOT NULL UNIQUE,
                           type VARCHAR(25) NOT NULL
);



INSERT INTO name_type (name, type)
VALUES
    ('Bulbasaur',  'grass'),
    ('Ivysaur',  'grass'),
    ('Venusaur',  'grass'),
    ('Charmander',  'fire'),
    ('Charmeleon',  'fire'),
    ('Charizard',  'fire'),
    ('Squirtle',  'water'),
    ('Wartortle',  'water'),
    ('Blastoise',  'water'),
    ('Caterpie',  'bug'),
    ('Metapod',  'bug'),
    ('Butterfree',  'bug'),
    ('Weedle',  'bug'),
    ('Kakuna',  'bug'),
    ('Beedrill',  'bug'),
    ('Pidgey',  'normal'),
    ('Pidgeotto',  'normal'),
    ('Pidgeot',  'normal'),
    ('Rattata',  'normal'),
    ('Raticate',  'normal'),
    ('Spearow',  'normal'),
    ('Fearow',  'normal'),
    ('Ekans',  'poison'),
    ('Arbok',  'poison'),
    ('Pikachu',  'electric'),
    ('Raichu',  'electric'),
    ('Sandshrew',  'ground'),
    ('Sandslash',  'ground'),
    ('Nidoran',  'poison'),
    ('Nidorina',  'poison'),
    ('Nidoqueen',  'poison'),
    ('Nidorino',  'poison'),
    ('Nidoking',  'poison'),
    ('Clefairy',  'normal'),
    ('Clefable',  'normal'),
    ('Vulpix',  'fire'),
    ('Ninetales',  'fire'),
    ('Jigglypuff',  'normal'),
    ('Wigglytuff',  'normal'),
    ('Zubat',  'poison'),
    ('Golbat',  'poison'),
    ('Oddish',  'grass'),
    ('Gloom',  'grass'),
    ('Vileplume',  'grass'),
    ('Paras',  'bug'),
    ('Parasect',  'bug'),
    ('Venonat',  'bug'),
    ('Venomoth',  'bug'),
    ('Diglett',  'ground'),
    ('Dugtrio',  'ground'),
    ('Meowth',  'normal'),
    ('Persian',  'normal'),
    ('Psyduck',  'water'),
    ('Golduck',  'water'),
    ('Mankey',  'fighting'),
    ('Primeape',  'fighting'),
    ('Growlithe',  'fire'),
    ('Arcanine',  'fire'),
    ('Poliwag',  'water'),
    ('Poliwhirl',  'water'),
    ('Poliwrath',  'water'),
    ('Abra',  'psychic'),
    ('Kadabra',  'psychic'),
    ('Alakazam',  'psychic'),
    ('Machop',  'fighting'),
    ('Machoke',  'fighting'),
    ('Machamp',  'fighting'),
    ('Bellsprout',  'grass'),
    ('Weepinbell',  'grass'),
    ('Victreebel',  'grass'),
    ('Tentacool',  'water'),
    ('Tentacruel',  'water'),
    ('Geodude',  'rock'),
    ('Graveler',  'rock'),
    ('Golem',  'rock'),
    ('Ponyta',  'fire'),
    ('Rapidash',  'fire'),
    ('Slowpoke',  'water'),
    ('Slowbro',  'water'),
    ('Magnemite',  'electric'),
    ('Magneton',  'electric'),
    ('Farfetchd',  'normal'),
    ('Doduo',  'normal'),
    ('Dodrio',  'normal'),
    ('Seel',  'water'),
    ('Dewgong',  'water'),
    ('Grimer',  'poison'),
    ('Muk',  'poison'),
    ('Shellder',  'water'),
    ('Cloyster',  'water'),
    ('Gastly',  'ghost'),
    ('Haunter',  'ghost'),
    ('Gengar',  'ghost'),
    ('Onix',  'rock'),
    ('Drowzee',  'psychic'),
    ('Hypno',  'psychic'),
    ('Krabby',  'water'),
    ('Kingler',  'water'),
    ('Voltorb',  'electric'),
    ('Electrode',  'electric'),
    ('Exeggcute',  'grass'),
    ('Exeggutor',  'grass'),
    ('Cubone',  'ground'),
    ('Marowak',  'ground'),
    ('Hitmonlee',  'fighting'),
    ('Hitmonchan',  'fighting'),
    ('Lickitung',  'normal'),
    ('Koffing',  'poison'),
    ('Weezing',  'poison'),
    ('Rhyhorn',  'ground'),
    ('Rhydon',  'ground'),
    ('Chansey',  'normal'),
    ('Tangela',  'grass'),
    ('Kangaskhan',  'normal'),
    ('Horsea',  'water'),
    ('Seadra',  'water'),
    ('Goldeen',  'water'),
    ('Seaking',  'water'),
    ('Staryu',  'water'),
    ('Starmie',  'water'),
    ('Mr Mime',  'psychic'),
    ('Scyther',  'bug'),
    ('Jynx',  'ice'),
    ('Electabuzz',  'electric'),
    ('Magmar',  'fire'),
    ('Pinsir',  'bug'),
    ('Tauros',  'normal'),
    ('Magikarp',  'water'),
    ('Gyarados',  'water'),
    ('Lapras',  'water'),
    ('Ditto',  'normal'),
    ('Eevee',  'normal'),
    ('Vaporeon',  'water'),
    ('Jolteon',  'electric'),
    ('Flareon',  'fire'),
    ('Porygon',  'normal'),
    ('Omanyte',  'rock'),
    ('Omastar',  'rock'),
    ('Kabuto',  'rock'),
    ('Kabutops',  'rock'),
    ('Aerodactyl',  'rock'),
    ('Snorlax',  'normal'),
    ('Articuno',  'ice'),
    ('Zapdos',  'electric'),
    ('Moltres',  'fire'),
    ('Dratini',  'dragon'),
    ('Dragonair',  'dragon'),
    ('Dragonite',  'dragon'),
    ('Mewtwo',  'psychic'),
    ('Mew',  'psychic');

CREATE TABLE trainer (
                         id INT PRIMARY KEY AUTO_INCREMENT,
                         name VARCHAR(30) NOT NULL UNIQUE
);


INSERT INTO trainer (name)
VALUES
    ('Bruno'),
    ('Agatha'),
    ('Sabrina'),
    ('Brock'),
    ('Erika'),
    ('Lorelei'),
    ('Lt. Surge'),
    ('Giovanni'),
    ('Lance');

CREATE TABLE pokemon (
                         id INT PRIMARY KEY AUTO_INCREMENT,
                         name_id INT NOT NULL,
                         trainer_id INT,
                         unique_trait VARCHAR(225) NOT NULL UNIQUE,
                         FOREIGN KEY (name_id) REFERENCES name_type(id),
                         FOREIGN KEY (trainer_id) REFERENCES trainer(id)
);



INSERT INTO pokemon (name_id, trainer_id, unique_trait)
VALUES
    (129, 9, 'red dot on head'),
    (141, 9, 'black mark on tail'),
    (6, 9, 'missing claw on left foot'),
    (31, 8, 'missing peace of left ear'),
    (110, 8, 'grayish than others'),
    (26, 7, 'bigger marks on cheecks'),
    (86, 6,  'missing dark mark on tail'),
    (130, 6, 'dark pink shell'),
    (70, 5, 'a lot small dark green marks on body'),
    (73, 4, 'two dark fingers on right hand'),
    (94, 4, 'realy dark third tail piece'),
    (64, 3, 'one kneepad is lighter'),
    (121, 3, 'its horns are round not sharp'),
    (93, 2, 'missing one tooth'),
    (41, 2, 'tear on right wing'),
    (24, 2, 'inner yellow piece is smaller than other'),
    (94, 1, 'broken horn'),
    (105, 1, 'dark mark between eyes'),
    (1, NULL, 'one ear darker'),
    (4, NULL, 'dark dots on belly'),
    (7, NULL, 'star shaped mark on left knee'),
    (25, NULL, 'dark spot on the tail is large'),
    (131, NULL, 'colored in old pink');
